version: "3.1"

services:
  # airflow:
  #   image: airflow:2.9.1
  #   volumes:
  #     - ./airflow:/opt/airflow
  #   ports:
  #     - "8081:8080"
  #   command: airflow standalone

  # mongo:
  #   image: mongo
  #   container_name: mongodb
  #   ports:
  #     - 27018:27017
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: nhanbui
  #   volumes:
  #     - ./data/mongodb/:/data/mongodb/

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka-broker-1:
    image: wurstmeister/kafka:latest
    mem_limit: '3g'
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  # kafka-broker-2:
  #   image: wurstmeister/kafka:latest
  #   mem_limit: '3g'
  #   ports:
  #     - "9094:9094"
  #   expose:
  #     - "9095"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://:9095,OUTSIDE://172.28.0.2:9094
  #     KAFKA_LISTENERS: INSIDE://:9095,OUTSIDE://:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181